import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
    ],

    theme: {
        extend: {
            colors: {
                "tertiary-fixed-dim": "#8acefb",
                "outline-variant": "#d6c3b3",
                "on-error-container": "#93000a",
                "surface-container-lowest": "#ffffff",
                "tertiary-container": "#046289",
                background: "#fcf9f3",
                "on-primary-fixed": "#2d1600",
                "surface-bright": "#fcf9f3",
                "on-tertiary": "#ffffff",
                "surface-container": "#f1ede8",
                "on-surface": "#1c1c19",
                "tertiary-fixed": "#c6e7ff",
                "inverse-on-surface": "#f3f0eb",
                "on-error": "#ffffff",
                "surface-tint": "#88520e",
                error: "#ba1a1a",
                "on-background": "#1c1c19",
                secondary: "#9f4121",
                "on-secondary-container": "#732103",
                "on-secondary-fixed-variant": "#802a0b",
                "secondary-container": "#fd8862",
                "surface-dim": "#dcdad4",
                "primary-container": "#854f0b",
                "surface-container-highest": "#e5e2dd",
                "on-surface-variant": "#524438",
                "inverse-surface": "#31302d",
                "on-tertiary-fixed": "#001e2e",
                surface: "#fcf9f3",
                "error-container": "#ffdad6",
                "primary-fixed": "#ffdcbe",
                "primary-fixed-dim": "#ffb870",
                tertiary: "#004968",
                "secondary-fixed-dim": "#ffb59e",
                primary: "#663a00",
                "surface-container-high": "#ebe8e2",
                "surface-container-low": "#f6f3ee",
                "on-primary": "#ffffff",
                "on-secondary": "#ffffff",
                "on-primary-container": "#ffca99",
                "on-primary-fixed-variant": "#693c00",
                "inverse-primary": "#ffb870",
                "on-tertiary-container": "#a6dbff",
                "secondary-fixed": "#ffdbd0",
                outline: "#847467",
                "on-secondary-fixed": "#3a0b00",
                "surface-variant": "#e5e2dd",
                "on-tertiary-fixed-variant": "#004c6c",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {},
            fontFamily: {
                headline: ["Inter"],
                body: ["Inter"],
                label: ["Inter"],
            },
        },
    },

    plugins: [forms],
};
