server{
    # Puerto en que Nginx escucha
    listen 80;
    server_name localhost;

    # Carpeta pública de Laravel (index.php vive aquí)
    root /var/www/public;
    index index.php index.html;

    # Si el archivo no existe, pasa la petición a index.php
    # Así funcionan las rutas de Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Manejo de archivos PHP → los pasa a PHP-FPM
    location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    # Ignora el archivo .htaccess (es de Apache, no de Nginx)
    location ~ /\.ht {
        deny all;
    }

}
